[dependencies]

[package]
  cjc-version = "0.0.1"
  name = "cangjie_experiments"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "--experimental --enable-eh -Woff unused"
  override-compile-option = ""
  link-option = ""

[package.package-configuration]

[target.aarch64-apple-darwin]                                                     
  [target.aarch64-apple-darwin.bin-dependencies]
    path-option = ["/Users/jacob/projects/resumptions-dev/software/darwin_aarch64_cjnative/dynamic/stdx"]

[target.x86_64-unknown-linux-gnu]                                                     
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["/home/pings/projects/cangjie/software/linux_x86_64_cjnative/dynamic/stdx"]
